[define]
  TELEGRAM_BOT_TOKEN = "8493484601:AAE1HYhkrfS-LdMZ90FcFOmt2lzgjqUekas"
  HELIUS_API_KEY = ""
  JUPITER_API_URL = "https://quote-api.jup.ag/v6"
  SUPABASE_URL = ""
  SUPABASE_KEY = ""
  MISSU_MINT = ""
  BURN_WALLET = "11111111111111111111111111111111"
  BOT_SOL_PAYER_SECRET = ""
  BIRDEYE_API_KEY = ""
  RPC_URL = "https://api.mainnet-beta.solana.com"
  PORT = "5000"
