-- Supabase schema for Missu burn bot

CREATE TABLE IF NOT EXISTS burns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mint text NOT NULL,
  amount numeric NOT NULL,
  fee numeric NOT NULL,
  tx text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sol_amount numeric NOT NULL,
  missu_amount numeric,
  tx text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS token_stats (
  mint text PRIMARY KEY,
  burned numeric DEFAULT 0
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id text NOT NULL,
  mint text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(chat_id, mint)
);
